FROM ghcr.io/renovatebot/renovate:44.88.0@sha256:3fd0987719c6c7a59c5e6d74f77735b6f3e1d1f657a8208c83bdf0935e94cf84

COPY ./apps/renovate/entrypoint.sh /entrypoint.sh
COPY ./apps/renovate/config.js.default /usr/src/app/config.js

ENTRYPOINT ["/entrypoint.sh"]
CMD ["renovate"]
