FROM ghcr.io/renovatebot/renovate:43.102.7@sha256:2ad0463bbbf515cf2824038a9d61c2a950b150f3e54a583acbae249d35759f7d

COPY ./apps/renovate/entrypoint.sh /entrypoint.sh
COPY ./apps/renovate/config.js.default /usr/src/app/config.js

ENTRYPOINT ["/entrypoint.sh"]
CMD ["renovate"]
