FROM ghcr.io/home-operations/stash:0.30.1@sha256:27d901751302236407f544bf45bd02c1b19eb33ee0a3e45333018ecfc28496d1

LABEL org.opencontainers.image.source=https://github.com/Syphiel/containers

USER root

# hadolint ignore=DL3018
RUN apk add --no-cache intel-media-driver py3-psycopg2 jellyfin-ffmpeg

USER $USER

ENTRYPOINT ["/usr/bin/catatonit", "--", "/entrypoint.sh"]
