FROM ghcr.io/home-operations/stash:0.31.1@sha256:12c4ee1424a211888f4e4253ef70b95a639b3d5475ea3d85e88989754569537d

LABEL org.opencontainers.image.source=https://github.com/Syphiel/containers

USER root

# hadolint ignore=DL3018
RUN apk add --no-cache intel-media-driver py3-psycopg2 jellyfin-ffmpeg

USER $USER

ENTRYPOINT ["/usr/bin/catatonit", "--", "/entrypoint.sh"]
