FROM ghcr.io/coder/code-server:4.109.5@sha256:f9ccfeb5a3de80d16342a6a842519c481522d80aafe65fb24a16393235a34f71 

LABEL org.opencontainers.image.source=https://github.com/Syphiel/containers

USER root

# hadolint ignore=DL3008
RUN apt-get update \
  && apt-get install --no-install-recommends -y \
    build-essential \
    lldb \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER $USER

ENTRYPOINT ["/usr/bin/entrypoint.sh", "--bind-addr", "0.0.0.0:8080", "."]
