FROM ghcr.io/coder/code-server:4.103.2@sha256:f9ed058d6b1a4aa80846f77902d344bd97e450aec69201a0f8939baf58b18a5f 

LABEL org.opencontainers.image.source=https://github.com/Syphiel/containers

USER root

# hadolint ignore=DL3008
RUN apt-get update \
  && apt-get install --no-install-recommends -y \
    build-essential \
    lldb \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

USER $USER

ENTRYPOINT ["/usr/bin/entrypoint.sh", "--bind-addr", "0.0.0.0:8080", "."]
