FROM alpine:3.24@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6

LABEL org.opencontainers.image.source=https://github.com/Syphiel/containers

# hadolint ignore=DL3018
RUN apk add --no-cache inotify-tools bash

COPY ./apps/gluetun-rutorrent-portforward/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
