FROM alpine:3.23@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659

LABEL org.opencontainers.image.source=https://github.com/Syphiel/containers

# hadolint ignore=DL3018
RUN apk add --no-cache inotify-tools bash

COPY ./apps/gluetun-rutorrent-portforward/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
